### ISSUE TITLE
Implement BCrypt

### ISSUE THREAD

**Issue by dipu-bd** [bitanon/hashlib#19]
https://en.wikipedia.org/wiki/Bcrypt

**Comment by dipu-bd** [comment]
https://github.com/patrickfav/bcrypt/blob/main/modules/bcrypt/src/main/java/at/favre/lib/crypto/bcrypt/BCrypt.java
https://github.com/patrickfav/bcrypt/blob/main/modules/bcrypt/src/test/java/at/favre/lib/crypto/bcrypt/BcryptTest.java

**Comment by NotTsunami** [comment]
+1
