### ISSUE TITLE
Argon2 is much slower (x146) with `dart run` than `dart compile && .exe`

### ISSUE THREAD

**Issue by rubenferreira97** [bitanon/hashlib#6]
I discovered this in one of my projects while hashing some passwords using Argon2.
Running the Argon2 benchmarks with `dart compile exe .\benchmark\benchmark.dart && .\benchmark\benchmark.exe` vs `dart run .\benchmark\benchmark.dart` results in a much slower experience `(438784ms vs 3080ms strong)`.

![argon_benchmarks](https://user-images.githubusercontent.com/43851289/225389985-64af03cb-30f6-4ebd-8ef3-290b7e731663.png)

Is this normal behavior?

**Comment by gmpassos** [comment]
I was looking the benchmark code, and there's NO warming phase for each benchmark before the "time measurement" phase.

When running benchmarks in a VM with JIT compilation it's very important to have a warming phase, where the VM will be able to compile the code with the current execution profile BEFORE the time measurement. Without that the benchmark is only measuring "interpreted" execution, which is very slow and won't represent real world scenarios.

**Comment by rubenferreira97** [comment]
In my own benchmark I executed the same function several times so jit warms up before the benchmark. I obtained the same slow results.

But even if jit is slower in a cold benchmark, does it make sense to be 150 times slower in such repetitive task (hashing)?

**Comment by dipu-bd** [comment]
@gmpassos I am running the `measure` function to get the runtime. It does warmup operation internally.

https://github.com/dipu-bd/hashlib/blob/c2f88287479b7a9a852dff3525d69cb799852075/benchmark/benchmark.dart#L140

Anyway, doing warmup actually does not affect the runtime much. The optimization suggestion from [mraleph](https://github.com/mraleph) in https://github.com/dart-lang/sdk/issues/51753 is interesting. I will try it out to check if it improves the performance.

**Comment by dipu-bd** [comment]
Well, it does improve the performance of `dart run` by a lot! The `pragma` is very useful here. I will be using these everywhere from now on. Sadly, their SDK documentation has no mention of it.

**Comment by gmpassos** [comment]
> @gmpassos I am running the `measure` function to get the runtime. It does warmup operation internally.
> 

Humm,

It seems that Argon2 is only set in the 2nd algorithms list:

https://github.com/dipu-bd/hashlib/blob/c2f88287479b7a9a852dff3525d69cb799852075/benchmark/benchmark.dart#L186

The 2nd list calls `run()`
https://github.com/dipu-bd/hashlib/blob/c2f88287479b7a9a852dff3525d69cb799852075/benchmark/benchmark.dart#L202

**Comment by mraleph** [comment]
@dipu-bd 

> Sadly, their SDK documentation has no mention of it.

FWIW

VM pragmas are documented here: https://github.com/dart-lang/sdk/blob/main/runtime/docs/pragmas.md
dart2js pragmas are documented here: https://github.com/dart-lang/sdk/blob/main/pkg/compiler/doc/pragmas.md

I noticed that you use `vm:always-consider-inlining` in few places, you should probably replace that with `vm:prefer-inline` instead. `always-consider-inlining` is a very specialised pragma which is mostly intended to be used in the code which has a lot of specialisation opportunities, see [example here](https://github.com/dart-lang/sdk/blob/20449a1ebc535d6f315680463f543c49e0c391a6/sdk/lib/_internal/vm/lib/array.dart#L118).

The rule of thumb with `prefer-inline` is that it should be put on functions which are either so small that calling them has unacceptable overhead (e.g. `mul32` is an example of such function) or expose some redundancies which can be effectively eliminated in the context of the caller (e.g. `List.get iterator`/`Iterator.moveNext`/`Iterator.get current` are an example - allocation of the iterator object is usually redundant in the context of the caller so inlining all involved methods allows compiler to produce better code). Annotating large methods with `prefer-inline` is discouraged - it usually will not lead to significant improvement in performance, but increase code size and compilation time unnecessary.

**Comment by dipu-bd** [comment]
Thanks for your guidance @mraleph
